# Generated by Django 4.1.3 on 2022-12-04 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название теста')),
                ('count', models.IntegerField(verbose_name='количество вопросов')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('date_edit', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
            ],
            options={
                'ordering': ['date_add'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='вопрос')),
                ('option_1', models.CharField(max_length=40, verbose_name='вариант 1')),
                ('option_2', models.CharField(max_length=40, verbose_name='вариант 2')),
                ('option_3', models.CharField(max_length=40, verbose_name='вариант 3')),
                ('option_4', models.CharField(max_length=40, verbose_name='вариант 4')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='тест')),
            ],
        ),
    ]
