# Generated by Django 4.1.3 on 2022-12-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.CharField(default='1', max_length=3, verbose_name='номер правильного ответа(ов)'),
        ),
    ]
