# Generated by Django 4.1.3 on 2022-12-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quiz_count_quiz_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField(default=0, verbose_name='correct')),
                ('incorrect', models.IntegerField(default=0, verbose_name='incorrect')),
            ],
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
    ]
