# Generated by Django 4.1.3 on 2022-12-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_question_correct_question_answ_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.CharField(default='', max_length=6),
        ),
    ]
